Fiverr par jab aapke paas bara dataset aata hai, toh manually ek ek column check karna mushkil hota hai. Pandas ki ye 5 tricks aapka ghanton ka kaam minto mein kar dengi:

### 1. df.info() aur df.describe()
Ye do commands aapko poore data ka "X-ray" karke de deti hain.

info(): Batata hai ke kis column mein kitni missing values hain aur data types kya hain.

describe(): Numbers wale columns ka Mean, Median, Min, aur Max nikal deta hai, jis se Outliers ka foran pata chal jata hai.

### 2. df.isnull().sum()
Client ko report deni ho ke data kitna ganda hai, toh ye command use karein. Ye har column ke hisab se missing values ki tadad bata deti hai.

### 3. value_counts() (For Categorical Data)
Agar aapke paas "City" ya "Gender" ka column hai, toh df['City'].value_counts() likhne se aapko pata chal jayega ke konsi city kitni baar aayi hai. Isse spelling mistakes (e.g., "Karachi" vs "Karchi") pakri jati hain.

### 4. df.drop_duplicates(inplace=True)
Sirf ek line likhne se hazaron rows mein se double entries khatam ho jati hain. Fiverr par clients aksar "Clean list of emails" ya "Unique leads" maangte hain, wahan ye best hai.

### 5. df.apply(lambda x: ...)
Ye sab se powerful trick hai. Agar aapne poore column mein koi khas tabdeeli karni hai (e.g., har price ke saath '$' sign lagana ya text ko format karna), toh apply function loop chalaye baghair foran kaam kar deta hai.

### Ek Expert Strategy:
Jab aap Fiverr par kaam karein, toh hamesha Jupyter Notebook use karein. Iska faida ye hai ke aap har step ka output (Table) client ko screenshot bhej kar dikha sakte hain ke "Dekhiye, pehle data aisa tha aur ab aisa hai."

Isse client ka trust barhta hai aur wo aapko achi rating deta hai.

In [1]:
import pandas as pd
bricks = {
    "country" : ['Brazil' , 'Russia' , 'India' , 'China' , 'South Africa'],
    "capital" : ['Brazil' , 'Moscow' , 'New Delhi' , 'Beijing' , 'Pretoria'],
    "area" : [8.516 , 17.100 , 3.286 , 9.597 , 1.221],
    "population" : [200.40 , 143.50 , 1252.00 , 1357.00 , 52.98]
}

df = pd.DataFrame(bricks , index=['Br','Ru','In','Ch','SA'])
df

         country    capital    area  population
Br        Brazil     Brazil   8.516      200.40
Ru        Russia     Moscow  17.100      143.50
In         India  New Delhi   3.286     1252.00
Ch         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [2]:
# call column one but show proper DataFrame
df[['country']]

         country
Br        Brazil
Ru        Russia
In         India
Ch         China
SA  South Africa

In [3]:
# call first two column
df[['country','capital']]

         country    capital
Br        Brazil     Brazil
Ru        Russia     Moscow
In         India  New Delhi
Ch         China    Beijing
SA  South Africa   Pretoria

In [4]:
# calls any two columns
df[['country','population']]

         country  population
Br        Brazil      200.40
Ru        Russia      143.50
In         India     1252.00
Ch         China     1357.00
SA  South Africa       52.98

In [5]:
# first two rows 
df[0:2]

   country capital    area  population
Br  Brazil  Brazil   8.516       200.4
Ru  Russia  Moscow  17.100       143.5

In [6]:
# any three rows call
df[2:5]

         country    capital   area  population
In         India  New Delhi  3.286     1252.00
Ch         China    Beijing  9.597     1357.00
SA  South Africa   Pretoria  1.221       52.98

In [7]:
# negative indexing 
df[-3:-1] # -1 not count

   country    capital   area  population
In   India  New Delhi  3.286      1252.0
Ch   China    Beijing  9.597      1357.0

In [8]:
df[-5:-3]

   country capital    area  population
Br  Brazil  Brazil   8.516       200.4
Ru  Russia  Moscow  17.100       143.5

In [9]:
# print first two rows & only first column 
df[0:2]['country']

Br    Brazil
Ru    Russia
Name: country, dtype: object

In [10]:
df[:2]['country']

Br    Brazil
Ru    Russia
Name: country, dtype: object

In [11]:
df[:2].country

Br    Brazil
Ru    Russia
Name: country, dtype: object

In [12]:
# print first two rows &  first two columns
df[0:2][['country','capital']]

   country capital
Br  Brazil  Brazil
Ru  Russia  Moscow

# Ab aap ye 5 Tasks perform karein:

1.Exploration: df.info() aur df.describe() run karein aur dekhein ke Age ka maximum kya hai aur Spent_Amount mein kitne values missing hain.

2.Missing Values: df.isnull().sum() check karein aur phir fillna() use karke Spent_Amount ki khali jaghon ko average (mean) se bhar dein.

3.Duplicates: df.drop_duplicates() use karke duplicate Customer IDs ko khatam karein.

4.Consistency: value_counts() se City check karein. Aap dekhenge ke 'Karachi' aur 'karachi' alag hain. Isay str.capitalize() ya replace() se theek karein.

5.Outliers: Age column mein jo '250' hai, usay kisi logic se (e.g., median age) replace karein.

In [2]:
import pandas as pd
import numpy as np

data = {
    "Customer_ID": [101,102,103,104,105,106,107,108,109,110,101],
    "Name": ["Ali","Sara","Ahmed","Ayesha","Bilal","Hina","Usman","Zara","Hamza","Noor","Ali"],
    "Age": [22,25,30,28,35,250,27,29,24,31,22],
    "City": ["Karachi","Lahore","karachi","Islamabad","Karachi","Lahore","karachi","Islamabad","Karachi","Lahore","Karachi"],
    "Spent_Amount": [2000,3000,None,4000,5000,None,3500,4200,3900,None,2000]
}

df = pd.DataFrame(data)
df

    Customer_ID    Name  Age       City  Spent_Amount
0           101     Ali   22    Karachi        2000.0
1           102    Sara   25     Lahore        3000.0
2           103   Ahmed   30    karachi           NaN
3           104  Ayesha   28  Islamabad        4000.0
4           105   Bilal   35    Karachi        5000.0
5           106    Hina  250     Lahore           NaN
6           107   Usman   27    karachi        3500.0
7           108    Zara   29  Islamabad        4200.0
8           109   Hamza   24    Karachi        3900.0
9           110    Noor   31     Lahore           NaN
10          101     Ali   22    Karachi        2000.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Customer_ID   11 non-null     int64
 1   Name          11 non-null     object
 2   Age           11 non-null     int64
 3   City          11 non-null     object
 4   Spent_Amount  8 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 572.0+ bytes

In [4]:
df.describe() #Describe() method only numerical features ka result dyta ha

       Customer_ID         Age  Spent_Amount
count    11.000000   11.000000      8.000000
mean    105.090909   47.545455   3450.000000
std       3.176619   67.262714   1060.996836
min     101.000000   22.000000   2000.000000
25%     102.500000   24.500000   2750.000000
50%     105.000000   28.000000   3700.000000
75%     107.500000   30.500000   4050.000000
max     110.000000  250.000000   5000.000000

In [5]:
print('This is Outlier',df['Age'].max())

This is Outlier 250

In [6]:
df['Spent_Amount'].isnull()

0     False
1     False
2      True
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10    False
Name: Spent_Amount, dtype: bool

In [7]:
df['Spent_Amount'].count()  #rows 8 count ki ha q k nan count nahi hogi

np.int64(8)

Task:2

In [8]:
df['Spent_Amount'].isnull().sum() #or ab nan ko count krwaya gya

np.int64(3)

In [9]:
df.loc[[2,5,9] , 'Spent_Amount'] = df['Spent_Amount'].mean()
df

    Customer_ID    Name  Age       City  Spent_Amount
0           101     Ali   22    Karachi        2000.0
1           102    Sara   25     Lahore        3000.0
2           103   Ahmed   30    karachi        3450.0
3           104  Ayesha   28  Islamabad        4000.0
4           105   Bilal   35    Karachi        5000.0
5           106    Hina  250     Lahore        3450.0
6           107   Usman   27    karachi        3500.0
7           108    Zara   29  Islamabad        4200.0
8           109   Hamza   24    Karachi        3900.0
9           110    Noor   31     Lahore        3450.0
10          101     Ali   22    Karachi        2000.0

Task:3

In [10]:
df['Customer_ID'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: Customer_ID, dtype: bool

In [11]:
df['Customer_ID'].drop_duplicates()

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: Customer_ID, dtype: int64

In [12]:
df['Customer_ID'] = df['Customer_ID'].drop_duplicates()
df

    Customer_ID    Name  Age       City  Spent_Amount
0         101.0     Ali   22    Karachi        2000.0
1         102.0    Sara   25     Lahore        3000.0
2         103.0   Ahmed   30    karachi        3450.0
3         104.0  Ayesha   28  Islamabad        4000.0
4         105.0   Bilal   35    Karachi        5000.0
5         106.0    Hina  250     Lahore        3450.0
6         107.0   Usman   27    karachi        3500.0
7         108.0    Zara   29  Islamabad        4200.0
8         109.0   Hamza   24    Karachi        3900.0
9         110.0    Noor   31     Lahore        3450.0
10          NaN     Ali   22    Karachi        2000.0

In [13]:
df.loc[10 , 'Customer_ID'] = 111
df

    Customer_ID    Name  Age       City  Spent_Amount
0         101.0     Ali   22    Karachi        2000.0
1         102.0    Sara   25     Lahore        3000.0
2         103.0   Ahmed   30    karachi        3450.0
3         104.0  Ayesha   28  Islamabad        4000.0
4         105.0   Bilal   35    Karachi        5000.0
5         106.0    Hina  250     Lahore        3450.0
6         107.0   Usman   27    karachi        3500.0
7         108.0    Zara   29  Islamabad        4200.0
8         109.0   Hamza   24    Karachi        3900.0
9         110.0    Noor   31     Lahore        3450.0
10        111.0     Ali   22    Karachi        2000.0

Task:4

In [14]:
df['City'].value_counts()

City
Karachi      4
Lahore       3
karachi      2
Islamabad    2
Name: count, dtype: int64

Difference

In [15]:
df.loc[[2,6],'City'] = df['City'].replace('karachi' , 'Karachi')
df

    Customer_ID    Name  Age       City  Spent_Amount
0         101.0     Ali   22    Karachi        2000.0
1         102.0    Sara   25     Lahore        3000.0
2         103.0   Ahmed   30    Karachi        3450.0
3         104.0  Ayesha   28  Islamabad        4000.0
4         105.0   Bilal   35    Karachi        5000.0
5         106.0    Hina  250     Lahore        3450.0
6         107.0   Usman   27    Karachi        3500.0
7         108.0    Zara   29  Islamabad        4200.0
8         109.0   Hamza   24    Karachi        3900.0
9         110.0    Noor   31     Lahore        3450.0
10        111.0     Ali   22    Karachi        2000.0

Difference

In [16]:
df['City'].value_counts()

City
Karachi      6
Lahore       3
Islamabad    2
Name: count, dtype: int64

Task:5

In [17]:
print('This is Outlier',df['Age'].max())

This is Outlier 250

In [ ]:
# Handle Outlier
df.loc[5 , 'Age'] = df['Age'].mean()*1.5
df

C:\Users\Muhammad Yahya\AppData\Local\Temp\ipykernel_13504\3211773751.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '71.31818181818181' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[5 , 'Age'] = df['Age'].mean()*1.5

    Customer_ID    Name        Age       City  Spent_Amount
0         101.0     Ali  22.000000    Karachi        2000.0
1         102.0    Sara  25.000000     Lahore        3000.0
2         103.0   Ahmed  30.000000    Karachi        3450.0
3         104.0  Ayesha  28.000000  Islamabad        4000.0
4         105.0   Bilal  35.000000    Karachi        5000.0
5         106.0    Hina  71.318182     Lahore        3450.0
6         107.0   Usman  27.000000    Karachi        3500.0
7         108.0    Zara  29.000000  Islamabad        4200.0
8         109.0   Hamza  24.000000    Karachi        3900.0
9         110.0    Noor  31.000000     Lahore        3450.0
10        111.0     Ali  22.000000    Karachi        2000.0