In [2]:
import pandas as pd
data = {
    'Name':['Ali','Umar','Arif','Hasan','Usman','Farooq','Afnan','Imtiaz'],
    'Age':[20 , 30 , 24 , 21 , 22 , 39 , 35 , 28],
    'Salary':[50000,200000,100000,500000,180000,199000,2500000,390000],
    'Performance Source':[85,90,78,92,88,80,89,91]

}

df = pd.DataFrame(data)
df

     Name  Age   Salary  Performance Source
0     Ali   20    50000                  85
1    Umar   30   200000                  90
2    Arif   24   100000                  78
3   Hasan   21   500000                  92
4   Usman   22   180000                  88
5  Farooq   39   199000                  80
6   Afnan   35  2500000                  89
7  Imtiaz   28   390000                  91

In [3]:
# add new column in dataset
df['Bonus'] = df['Salary']*1.5
df

     Name  Age   Salary  Performance Source      Bonus
0     Ali   20    50000                  85    75000.0
1    Umar   30   200000                  90   300000.0
2    Arif   24   100000                  78   150000.0
3   Hasan   21   500000                  92   750000.0
4   Usman   22   180000                  88   270000.0
5  Farooq   39   199000                  80   298500.0
6   Afnan   35  2500000                  89  3750000.0
7  Imtiaz   28   390000                  91   585000.0

In [4]:
# salary update
# increasing salary in 5% 
df['Salary'] = df['Salary']*1.05
df

     Name  Age     Salary  Performance Source      Bonus
0     Ali   20    52500.0                  85    75000.0
1    Umar   30   210000.0                  90   300000.0
2    Arif   24   105000.0                  78   150000.0
3   Hasan   21   525000.0                  92   750000.0
4   Usman   22   189000.0                  88   270000.0
5  Farooq   39   208950.0                  80   298500.0
6   Afnan   35  2625000.0                  89  3750000.0
7  Imtiaz   28   409500.0                  91   585000.0

In [5]:
# Bonus update
# increasing Bonus in 5% 
df['Bonus'] = df['Bonus']*1.05
df

     Name  Age     Salary  Performance Source      Bonus
0     Ali   20    52500.0                  85    78750.0
1    Umar   30   210000.0                  90   315000.0
2    Arif   24   105000.0                  78   157500.0
3   Hasan   21   525000.0                  92   787500.0
4   Usman   22   189000.0                  88   283500.0
5  Farooq   39   208950.0                  80   313425.0
6   Afnan   35  2625000.0                  89  3937500.0
7  Imtiaz   28   409500.0                  91   614250.0

In [42]:
data = {
    'Name':['Ali','Umar','Arif','Hasan','Usman','Farooq','Afnan','Imtiaz'],
    'Age':[20 , 30 , 24 , 21 , 22 , 39 , 35 , 28],
    'Salary':[50000,200000,100000,500000,180000,199000,2500000,390000],
    'Performance Source':[85,90,78,92,88,80,89,91]

}

df = pd.DataFrame(data)
df

     Name  Age   Salary  Performance Source
0     Ali   20    50000                  85
1    Umar   30   200000                  90
2    Arif   24   100000                  78
3   Hasan   21   500000                  92
4   Usman   22   180000                  88
5  Farooq   39   199000                  80
6   Afnan   35  2500000                  89
7  Imtiaz   28   390000                  91

In [7]:
# Remove perticular column 
# using drop()
df.drop(columns=['Performance Source'] , inplace=True)
df

     Name  Age   Salary
0     Ali   20    50000
1    Umar   30   200000
2    Arif   24   100000
3   Hasan   21   500000
4   Usman   22   180000
5  Farooq   39   199000
6   Afnan   35  2500000
7  Imtiaz   28   390000

In [41]:
# isnull() Method
# - Data jahan jahan missing ha means None ha wahan 'True' milay ga
data = {
    'Name':['Ali',None,'Arif','Hasan','Usman','Farooq','Afnan','Imtiaz'],
    'Age':[20 , None , 24 , 21 , 22 , 39 , 35 , 28],
    'Salary':[50000,None,100000,500000,180000,199000,2500000,390000],
    'Performance Source':[85,None,78,92,88,80,89,91]

}

df = pd.DataFrame(data)
df

     Name   Age     Salary  Performance Source
0     Ali  20.0    50000.0                85.0
1    None   NaN        NaN                 NaN
2    Arif  24.0   100000.0                78.0
3   Hasan  21.0   500000.0                92.0
4   Usman  22.0   180000.0                88.0
5  Farooq  39.0   199000.0                80.0
6   Afnan  35.0  2500000.0                89.0
7  Imtiaz  28.0   390000.0                91.0

In [9]:
df.isnull()

    Name    Age  Salary  Performance Source
0  False  False   False               False
1   True   True    True                True
2  False  False   False               False
3  False  False   False               False
4  False  False   False               False
5  False  False   False               False
6  False  False   False               False
7  False  False   False               False

In [10]:
# isnull().sum() method
# kon sy column main kitni values missing ha wahan
data = {
    'Name':['Ali',None,'Arif','Hasan','Usman','Farooq','Afnan','Imtiaz'],
    'Age':[20 , None , 24 , 21 , 22 , 39 , 35 , 28],
    'Salary':[50000,None,100000,500000,180000,199000,2500000,390000],
    'Performance Source':[85,None,78,92,88,80,89,91]

}
df = pd.DataFrame(data)
df

     Name   Age     Salary  Performance Source
0     Ali  20.0    50000.0                85.0
1    None   NaN        NaN                 NaN
2    Arif  24.0   100000.0                78.0
3   Hasan  21.0   500000.0                92.0
4   Usman  22.0   180000.0                88.0
5  Farooq  39.0   199000.0                80.0
6   Afnan  35.0  2500000.0                89.0
7  Imtiaz  28.0   390000.0                91.0

In [11]:
df.isnull().sum()

Name                  1
Age                   1
Salary                1
Performance Source    1
dtype: int64

In [12]:
# - Missing values ko pta krnay k baad do raasty hain 
# value Remove ya fill

# 1. dropna(axis=0 , inplace=True)
# axis=0 means missing values wali rows remove hogi
# axis=1 means missing values wala column remove hoga

df.dropna(axis=0 , inplace=True)
df

     Name   Age     Salary  Performance Source
0     Ali  20.0    50000.0                85.0
2    Arif  24.0   100000.0                78.0
3   Hasan  21.0   500000.0                92.0
4   Usman  22.0   180000.0                88.0
5  Farooq  39.0   199000.0                80.0
6   Afnan  35.0  2500000.0                89.0
7  Imtiaz  28.0   390000.0                91.0

In [40]:
# fillna() method
data = {
    'Name':['Ali',None,'Arif','Hasan','Usman','Farooq','Afnan','Imtiaz'],
    'Age':[20 , None , 24 , 21 , 22 , 39 , 35 , 28],
    'Salary':[50000,None,100000,500000,180000,199000,2500000,390000],
    'Performance Source':[85,None,78,92,88,80,89,91]

}

df = pd.DataFrame(data)
df

     Name   Age     Salary  Performance Source
0     Ali  20.0    50000.0                85.0
1    None   NaN        NaN                 NaN
2    Arif  24.0   100000.0                78.0
3   Hasan  21.0   500000.0                92.0
4   Usman  22.0   180000.0                88.0
5  Farooq  39.0   199000.0                80.0
6   Afnan  35.0  2500000.0                89.0
7  Imtiaz  28.0   390000.0                91.0

In [14]:
df.fillna(0 , inplace=True)
df

     Name   Age     Salary  Performance Source
0     Ali  20.0    50000.0                85.0
1       0   0.0        0.0                 0.0
2    Arif  24.0   100000.0                78.0
3   Hasan  21.0   500000.0                92.0
4   Usman  22.0   180000.0                88.0
5  Farooq  39.0   199000.0                80.0
6   Afnan  35.0  2500000.0                89.0
7  Imtiaz  28.0   390000.0                91.0

In [15]:
# pandas main interpolation aik estimate nikalta ha aik numerical column ki
# yaad rahy sirf numerical column sy
data = {
    'Name':['Ali',None,'Arif','Hasan','Usman','Farooq','Afnan','Imtiaz'],
    'Age':[20 , None , 24 , 21 , 22 , 39 , 35 , 28],
    'Salary':[50000,None,100000,500000,180000,199000,2500000,390000],
    'Performance Source':[85,None,78,92,88,80,89,91]

}
df = pd.DataFrame(data)
df

     Name   Age     Salary  Performance Source
0     Ali  20.0    50000.0                85.0
1    None   NaN        NaN                 NaN
2    Arif  24.0   100000.0                78.0
3   Hasan  21.0   500000.0                92.0
4   Usman  22.0   180000.0                88.0
5  Farooq  39.0   199000.0                80.0
6   Afnan  35.0  2500000.0                89.0
7  Imtiaz  28.0   390000.0                91.0

In [17]:
# linear , polynomial , time
df.interpolate(method='linear' , axis=0 , inplace=True) #numerical column main missing values ko fill krta ha sequence k hisaab sy
df

C:\Users\Muhammad Yahya\AppData\Local\Temp\ipykernel_4972\1383885910.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear' , axis=0 , inplace=True) #numerical column main missing values ko fill krta ha sequence k hisaab sy

     Name   Age     Salary  Performance Source
0     Ali  20.0    50000.0                85.0
1    None  22.0    75000.0                81.5
2    Arif  24.0   100000.0                78.0
3   Hasan  21.0   500000.0                92.0
4   Usman  22.0   180000.0                88.0
5  Farooq  39.0   199000.0                80.0
6   Afnan  35.0  2500000.0                89.0
7  Imtiaz  28.0   390000.0                91.0

USES: interpolate()

1.Time series data

2.numeric data with trends 

3.Avoid droping raws

In [39]:
datas = {
    'Time':[1,2,3,4,5],
    'Values':[1,None,3,None,5]
}

df = pd.DataFrame(datas)
df

   Time  Values
0     1     1.0
1     2     NaN
2     3     3.0
3     4     NaN
4     5     5.0

In [38]:
datas = {
    'Name':['JOHN' , 'ANDREW' , 'EIGEN ROSUM'],
    'Age':[29 , 20 , 23],
    'Gender':1

}

df = pd.DataFrame(datas)
df

          Name  Age  Gender
0         JOHN   29       1
1       ANDREW   20       1
2  EIGEN ROSUM   23       1

In [32]:
# single column sort values
# sort_values() 
# syntax:- 
# df.sort_values(by='column name' , ascending=True ya False , inpalce=True)

df.sort_values(by='Age' , ascending=True , inplace=True)
df

          Name  Age  Gender
1       ANDREW   20       1
2  EIGEN ROSUM   23       1
0         JOHN   29       1

In [34]:
# sort multiple columns 
datas = {
    'Name':['JOHN' , 'ANDREW' , 'EIGEN ROSUM'],
    'Age':[29 , 20 , 23],
    'Salary':[20000.0 , 100000.0 , 450000.0],
    'Gender':1

}
df = pd.DataFrame(datas)
df

          Name  Age    Salary  Gender
0         JOHN   29   20000.0       1
1       ANDREW   20  100000.0       1
2  EIGEN ROSUM   23  450000.0       1

In [35]:
df.sort_values(by=['Age','Salary'] , ascending=False , inplace=True)
df

          Name  Age    Salary  Gender
0         JOHN   29   20000.0       1
2  EIGEN ROSUM   23  450000.0       1
1       ANDREW   20  100000.0       1

aggregation:

1.summary statistics 

df['column name].mean()

df['column name].min()

df['column name'].max()

df['column name'].sum()

In [58]:
datas = {
    'Name':['JOHN' , 'ANDREW' , 'EIGEN ROSUM'],
    'Age':[29 , 20 , 23],
    'Salary':[20000.0 , 100000.0 , 450000.0],
    'Gender':1

}

df = pd.DataFrame(datas)
df

          Name  Age    Salary  Gender
0         JOHN   29   20000.0       1
1       ANDREW   20  100000.0       1
2  EIGEN ROSUM   23  450000.0       1

In [59]:
avg_salary = df['Salary'].mean()
avg_salary

np.float64(190000.0)

In [60]:
min_salary = df['Salary'].min()
min_salary

np.float64(20000.0)

In [61]:
max_salary = df['Salary'].max()
max_salary

np.float64(450000.0)

In [62]:
sum_Salary = df['Salary'].sum()
sum_Salary

np.float64(570000.0)

In [ ]:
avg_age_salary = df[['Age' , 'Salary']].mean()
avg_age_salary #Age ka avg float main diya ha q k python data ka loss nahi krta

Age           24.0
Salary    190000.0
dtype: float64

In [ ]:
min_salary_age = df[['Salary' , 'Age']].min()
min_salary_age #Min age float main diya ha q k python data ka loss nahi krta

Salary    20000.0
Age          20.0
dtype: float64