# Topic:  Delete and Insert DATA:

In [164]:
import pandas as pd

In [165]:
df = pd.DataFrame({'A':[1 , 3 , 4 ,6 , 8] , 'B':[2 , 5 , 7 , 9 , 10]})
df

   A   B
0  1   2
1  3   5
2  4   7
3  6   9
4  8  10

insert() method1

In [166]:
# insert() fn
df.insert(0 , 'Python' , df['A'])  #insert column into DataFrame at specified location.
df

   Python  A   B
0       1  1   2
1       3  3   5
2       4  4   7
3       6  6   9
4       8  8  10

### OR  Method2

In [167]:
df.insert(1 , 'Numpy' , [8,6,4,3,1])
df

   Python  Numpy  A   B
0       1      8  1   2
1       3      6  3   5
2       4      4  4   7
3       6      3  6   9
4       8      1  8  10

In [168]:
# CREATE NEW COLUMN AND STORE FROM COLUMN A --->  FIRTST THREE ROWS
df.insert(2 , 'Matplotlib' , df.loc[0:2 , 'A'])
df

   Python  Numpy  Matplotlib  A   B
0       1      8         1.0  1   2
1       3      6         3.0  3   5
2       4      4         4.0  4   7
3       6      3         NaN  6   9
4       8      1         NaN  8  10

OR

In [169]:
df['ScikitLearn'] = df['A'][0:3]
df

   Python  Numpy  Matplotlib  A   B  ScikitLearn
0       1      8         1.0  1   2          1.0
1       3      6         3.0  3   5          3.0
2       4      4         4.0  4   7          4.0
3       6      3         NaN  6   9          NaN
4       8      1         NaN  8  10          NaN

### DELETE COLUMN  
USING POP()

In [170]:
df_dic = pd.DataFrame({'A':[20 , 25 , 30 , 35] , 'B':[40 , 45 , 50 , 55] , 'C':[60 , 65, 70 , 75]})
df_dic

    A   B   C
0  20  40  60
1  25  45  65
2  30  50  70
3  35  55  75

In [171]:
df_dic.pop('C') #DELETE COLUMN C

0    60
1    65
2    70
3    75
Name: C, dtype: int64

In [172]:
df_dic #after deletion

    A   B
0  20  40
1  25  45
2  30  50
3  35  55

OR

USING del keyward

In [173]:
del df_dic['A']
df_dic

    B
0  40
1  45
2  50
3  55

# PRACTICE TIME

In [174]:
df = pd.DataFrame({'JuniorDataScientist':['Py','Numpy','Pandas','Matplotlib','SQL'],
                   'JunoirMachineLearningEngg':['Sklearn','Py','Numpy','Pandas','Matplotlib']})

df

  JuniorDataScientist JunoirMachineLearningEngg
0                  Py                   Sklearn
1               Numpy                        Py
2              Pandas                     Numpy
3          Matplotlib                    Pandas
4                 SQL                Matplotlib

In [175]:
df.insert(0 , 'JuniorAI_Developer' , ['Py','Numpy','Matplotlib','Pandas','SQL + Sklearn']) #Insert column into DataFrame at specified location.
df

  JuniorAI_Developer JuniorDataScientist JunoirMachineLearningEngg
0                 Py                  Py                   Sklearn
1              Numpy               Numpy                        Py
2         Matplotlib              Pandas                     Numpy
3             Pandas          Matplotlib                    Pandas
4      SQL + Sklearn                 SQL                Matplotlib

In [176]:
df.insert(3 , 'MachineLearningIntern' , df['JunoirMachineLearningEngg'])
df

,JuniorAI_Developer,JuniorDataScientist,JunoirMachineLearningEngg,MachineLearningIntern
0,Py,Py,Sklearn,Sklearn
1,Numpy,Numpy,Py,Py
2,Matplotlib,Pandas,Numpy,Numpy
3,Pandas,Matplotlib,Pandas,Pandas
4,SQL + Sklearn,SQL,Matplotlib,Matplotlib

In [177]:
df.pop('MachineLearningIntern')

0       Sklearn
1            Py
2         Numpy
3        Pandas
4    Matplotlib
Name: MachineLearningIntern, dtype: object

In [178]:
df

  JuniorAI_Developer JuniorDataScientist JunoirMachineLearningEngg
0                 Py                  Py                   Sklearn
1              Numpy               Numpy                        Py
2         Matplotlib              Pandas                     Numpy
3             Pandas          Matplotlib                    Pandas
4      SQL + Sklearn                 SQL                Matplotlib

In [179]:
del df['JuniorAI_Developer']
df

  JuniorDataScientist JunoirMachineLearningEngg
0                  Py                   Sklearn
1               Numpy                        Py
2              Pandas                     Numpy
3          Matplotlib                    Pandas
4                 SQL                Matplotlib