In [14]:
import seaborn as sns

In [26]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [28]:
# jitni bhi null values wali rows hain wo sb eliminate ho joe ga 
df.dropna(how='any' , inplace=True)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [31]:
import pandas as pd

In [36]:
df = pd.DataFrame(
    {
    'Name':['a', None , 'c' , 'd' , None , 'f'],
    'Age':[20 , None , 30 , 35 , None , 39],
    'Salary':[200000 , None , 210000 , 300000 ,None , None] 
})

df

   Name   Age    Salary
0     a  20.0  200000.0
1  None   NaN       NaN
2     c  30.0  210000.0
3     d  35.0  300000.0
4  None   NaN       NaN
5     f  39.0       NaN

In [37]:
# how='all' parameter ye krta ha k complete null values wali row ko hi eleiminate krta ha jahan complete row main null values nahi wahan null hi rehna dyga
df.dropna(how='all' , inplace=True)
df

  Name   Age    Salary
0    a  20.0  200000.0
2    c  30.0  210000.0
3    d  35.0  300000.0
5    f  39.0       NaN

In [35]:
df = pd.DataFrame(
    {
    'Name':['a', None , 'c' , 'd' , None , 'f'],
    'Age':[20 , None , 30 , 35 , None , 39],
    'Salary':[200000 , None , 210000 , 300000 ,None , None] 
})

df

   Name   Age    Salary
0     a  20.0  200000.0
1  None   NaN       NaN
2     c  30.0  210000.0
3     d  35.0  300000.0
4  None   NaN       NaN
5     f  39.0       NaN

In [39]:
df.dropna(how='any' , inplace=True)
df

  Name   Age    Salary
0    a  20.0  200000.0
2    c  30.0  210000.0
3    d  35.0  300000.0

In [ ]:
# kici aik particular column ki value remove krnay k liyay
# df.dropna(subset=['Column_name'])
# but jo partiular column ki null value ko remove kre gy tou wo complete row remove hogi 
df = pd.DataFrame(
    {
    'Name':['a', None , 'c' , 'd' , None , 'f'],
    'Age':[20 , 26 , 30 , 35 , None , 39],
    'Salary':[200000 , 290000 , 210000 , 300000 ,None , None] 
})

df

   Name   Age    Salary
0     a  20.0  200000.0
1  None  26.0  290000.0
2     c  30.0  210000.0
3     d  35.0  300000.0
4  None   NaN       NaN
5     f  39.0       NaN

In [42]:
df.dropna(subset=['Name'] , inplace=True)
df

  Name   Age    Salary
0    a  20.0  200000.0
2    c  30.0  210000.0
3    d  35.0  300000.0
5    f  39.0       NaN

In [43]:
df.dropna(subset=['Salary'] , inplace=True)
df

  Name   Age    Salary
0    a  20.0  200000.0
2    c  30.0  210000.0
3    d  35.0  300000.0

# Summary ---> inplace parameter: 
Common Pandas Methods That Support inplace:-

Category	Method	Description:

Data Cleaning	drop(labels, axis, inplace)	Remove rows or columns

dropna(inplace)	Remove missing values

fillna(value, inplace)	Fill missing values

replace(to_replace, value, inplace)	Replace specific values

rename(mapper, inplace)	Rename columns or index

set_index(keys, inplace)	Set a column as index

reset_index(inplace)	Reset the index to default

sort_values(by, inplace)	Sort by values in a column

sort_index(inplace)	Sort by index

clip(lower, upper, inplace)	Limit values between boundaries

update(other, inplace)	Update values from another DataFrame

astype(dtype, inplace)	Change data types (new in pandas 2.0+)