## loc and iloc for PANDAS In selection Data

# 1.loc — Label-based Indexing
loc tab use hota hai jab aap row ya column ka naam (label) use kar ke data select karna chahte hain.

Yani: Row/Column ka NAAM likhte hain

# 2. iloc — Position-based Indexing
iloc tab use hota hai jab aap row or column ki numeric position se data select karte hain.

Yani: Row numbers (0,1,2...) use hote hain

In [1]:
import seaborn as sns

In [3]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [5]:
df.head(12)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

In [19]:
df.loc[0:6 , 'sex':'sibsp']

      sex   age  sibsp
0    male  22.0      1
1  female  38.0      1
2  female  26.0      0
3  female  35.0      1
4    male  35.0      0
5    male   NaN      0
6    male  54.0      0

DIFF B/W ABOVE AND BELOW

In [20]:
df.loc[0:6 , ['sex' , 'sibsp']]

      sex  sibsp
0    male      1
1  female      1
2  female      0
3  female      1
4    male      0
5    male      0
6    male      0

In [26]:
df.loc[:7 , ['sex' , 'sibsp']]

      sex  sibsp
0    male      1
1  female      1
2  female      0
3  female      1
4    male      0
5    male      0
6    male      0
7    male      3

In [29]:
df.loc[2:18 , ['survived','age']]

    survived   age
2          1  26.0
3          1  35.0
4          0  35.0
5          0   NaN
6          0  54.0
7          0   2.0
8          1  27.0
9          1  14.0
10         1   4.0
11         1  58.0
12         0  20.0
13         0  39.0
14         0  14.0
15         1  55.0
16         0   2.0
17         1   NaN
18         0  31.0

In [31]:
df.loc[[2,18] , 'survived':'age']

    survived  pclass     sex   age
2          1       3  female  26.0
18         0       3  female  31.0

In [32]:
df.loc[[2:18] , 'survived':'age'] #Error

SyntaxError: invalid syntax (2267335054.py, line 1)

In [38]:
df.loc[50:70 , ['survived','age']]

    survived   age
50         0   7.0
51         0  21.0
52         1  49.0
53         1  29.0
54         0  65.0
55         1   NaN
56         1  21.0
57         0  28.5
58         1   5.0
59         0  11.0
60         0  22.0
61         1  38.0
62         0  45.0
63         0   4.0
64         0   NaN
65         1   NaN
66         1  29.0
67         0  19.0
68         1  17.0
69         0  26.0
70         0  32.0

In [ ]:
df.loc[50:70 , ['survived':'age']] #Error

SyntaxError: invalid syntax (3633084053.py, line 1)

In [49]:
df.loc[[1,25,50,75,100,125,150] , 'survived':'age']

     survived  pclass     sex   age
1           1       1  female  38.0
25          1       3  female  38.0
50          0       3    male   7.0
75          0       3    male  25.0
100         0       3  female  28.0
125         1       3    male  12.0
150         0       2    male  51.0

In [50]:
# yahan error milay ga Q K loc fn main column name dyna hoga 
df.loc[0:15 , 5:8]

TypeError: cannot do slice indexing on Index with these indexers [5] of type int

. Above wala Error solve hoga iloc fn sy

. iloc k fn main last index not included

In [51]:
# using iloc fun
df.iloc[0:15 , 5:8]

    parch     fare embarked
0       0   7.2500        S
1       0  71.2833        C
2       0   7.9250        S
3       0  53.1000        S
4       0   8.0500        S
5       0   8.4583        Q
6       0  51.8625        S
7       1  21.0750        S
8       2  11.1333        S
9       0  30.0708        C
10      1  16.7000        S
11      0  26.5500        S
12      0   8.0500        S
13      5  31.2750        S
14      0   7.8542        S

In [54]:
df.iloc[[1,5,10,15,20,50,75,95,120] , [0,2,3]]

     survived     sex   age
1           1  female  38.0
5           0    male   NaN
10          1  female   4.0
15          1  female  55.0
20          0    male  35.0
50          0    male   7.0
75          0    male  25.0
95          0    male   NaN
120         0    male  21.0

In [55]:
df.iloc[15:35 , 2:6]

       sex   age  sibsp  parch
15  female  55.0      0      0
16    male   2.0      4      1
17    male   NaN      0      0
18  female  31.0      1      0
19  female   NaN      0      0
20    male  35.0      0      0
21    male  34.0      0      0
22  female  15.0      0      0
23    male  28.0      0      0
24  female   8.0      3      1
25  female  38.0      1      5
26    male   NaN      0      0
27    male  19.0      3      2
28  female   NaN      0      0
29    male   NaN      0      0
30    male  40.0      0      0
31  female   NaN      1      0
32  female   NaN      0      0
33    male  66.0      0      0
34    male  28.0      1      0

In [ ]:
df.iloc[0:15 , 'Sex':'SibSp']  #Error (ye iloc pr nahi chalta)

TypeError: cannot do positional indexing on Index with these indexers [Sex] of type str

# DIFF B/W

In [61]:
df.iloc[0:15 , 2:5] #yahan chalta ha

       sex   age  sibsp
0     male  22.0      1
1   female  38.0      1
2   female  26.0      0
3   female  35.0      1
4     male  35.0      0
5     male   NaN      0
6     male  54.0      0
7     male   2.0      3
8   female  27.0      0
9   female  14.0      1
10  female   4.0      1
11  female  58.0      0
12    male  20.0      0
13    male  39.0      1
14  female  14.0      0

In [66]:
df.iloc[[0,15] , [2,4]]

       sex  sibsp
0     male      1
15  female      0


. loc main end indexing bhi include hogi

. iloc main end indexing nahi include hogi

In [70]:
# df.loc[InitialRowIndex : FinalRowIndex , InitialColumnName : FinalColumnName]
df.loc[1:4 , 'survived':'embarked']

   survived  pclass     sex   age  sibsp  parch     fare embarked
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

# PRACTICE

In [2]:
import seaborn as sns

In [3]:
df = sns.load_dataset('titanic')
df.head(15)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True

In [4]:
df.loc[0:19 , ['sex','age']]

       sex   age
0     male  22.0
1   female  38.0
2   female  26.0
3   female  35.0
4     male  35.0
5     male   NaN
6     male  54.0
7     male   2.0
8   female  27.0
9   female  14.0
10  female   4.0
11  female  58.0
12    male  20.0
13    male  39.0
14  female  14.0
15  female  55.0
16    male   2.0
17    male   NaN
18  female  31.0
19  female   NaN

In [5]:
df.loc[0:20 , 'pclass':'sibsp']

    pclass     sex   age  sibsp
0        3    male  22.0      1
1        1  female  38.0      1
2        3  female  26.0      0
3        1  female  35.0      1
4        3    male  35.0      0
5        3    male   NaN      0
6        1    male  54.0      0
7        3    male   2.0      3
8        3  female  27.0      0
9        2  female  14.0      1
10       3  female   4.0      1
11       1  female  58.0      0
12       3    male  20.0      0
13       3    male  39.0      1
14       3  female  14.0      0
15       2  female  55.0      0
16       3    male   2.0      4
17       2    male   NaN      0
18       3  female  31.0      1
19       3  female   NaN      0
20       2    male  35.0      0

In [6]:
df.loc[[0,10] , 'age':]

,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,22.0,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False
10,4.0,1,1,16.70,S,Third,child,False,G,Southampton,yes,False

In [7]:
df.loc[[0,10,20,30,60,80,99,100,120,150,180] , 'age']

0      22.0
10      4.0
20     35.0
30     40.0
60     22.0
80     22.0
99     34.0
100    28.0
120    21.0
150    51.0
180     NaN
Name: age, dtype: float64

In [8]:
df.loc[[0,10,20,30,60,80,99,100,120,150,180] , 'age':]

,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
10,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
20,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
30,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
60,22.0,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
80,22.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
99,34.0,1,0,26.0000,S,Second,man,True,NaN,Southampton,no,False
100,28.0,0,0,7.8958,S,Third,woman,False,NaN,Southampton,no,True
120,21.0,2,0,73.5000,S,Second,man,True,NaN,Southampton,no,False
150,51.0,0,0,12.5250,S,Second,man,True,NaN,Southampton,no,True
180,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False

In [9]:
df.loc[[0,50,100,150] , ['fare','age']]

        fare   age
0     7.2500  22.0
50   39.6875   7.0
100   7.8958  28.0
150  12.5250  51.0

In [10]:
avg = df.loc[[0,50,100,150] , ['fare','age']].mean()
avg

fare    16.839575
age     27.000000
dtype: float64

In [11]:

# Deviation:- formula:(xi=(each data points) - xbar=mean)
deviation = df.loc[[0,50,100,150],'fare'] - avg.fare
deviation

0      -9.589575
50     22.847925
100    -8.943775
150    -4.314575
Name: fare, dtype: float64

In [12]:
df.loc[[0,50,100,150] , 'fare':]

,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,7.2500,S,Third,man,True,NaN,Southampton,no,False
50,39.6875,S,Third,child,False,NaN,Southampton,no,False
100,7.8958,S,Third,woman,False,NaN,Southampton,no,True
150,12.5250,S,Second,man,True,NaN,Southampton,no,True

In [13]:
df.loc[[0,50,100,150] , 'fare':'alive']

        fare embarked   class    who  adult_male deck  embark_town alive
0     7.2500        S   Third    man        True  NaN  Southampton    no
50   39.6875        S   Third  child       False  NaN  Southampton    no
100   7.8958        S   Third  woman       False  NaN  Southampton    no
150  12.5250        S  Second    man        True  NaN  Southampton    no

In [14]:
df.iloc[0: , 0:]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [15]:
df.iloc[0:5 , 0:4] #iloc main last index include

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [16]:
df.iloc[[0,4,20,50,90,100,150,250,350,500] , [0,3,6,9]]

     survived   age     fare    who
0           0  22.0   7.2500    man
4           0  35.0   8.0500    man
20          0  35.0  26.0000    man
50          0   7.0  39.6875  child
90          0  29.0   8.0500    man
100         0  28.0   7.8958  woman
150         0  51.0  12.5250    man
250         0   NaN   7.2500    man
350         0  23.0   9.2250    man
500         0  17.0   8.6625    man

In [17]:
df.iloc[[0,4,20,50,90,100,150,250,350,500] , [0,3,6,9]]

     survived   age     fare    who
0           0  22.0   7.2500    man
4           0  35.0   8.0500    man
20          0  35.0  26.0000    man
50          0   7.0  39.6875  child
90          0  29.0   8.0500    man
100         0  28.0   7.8958  woman
150         0  51.0  12.5250    man
250         0   NaN   7.2500    man
350         0  23.0   9.2250    man
500         0  17.0   8.6625    man

In [18]:
df.iloc[[0,50,100,150,200,250,300,400,500] , [0,3,6]]

     survived   age     fare
0           0  22.0   7.2500
50          0   7.0  39.6875
100         0  28.0   7.8958
150         0  51.0  12.5250
200         0  28.0   9.5000
250         0   NaN   7.2500
300         1   NaN   7.7500
400         1  39.0   7.9250
500         0  17.0   8.6625

In [22]:
avg = df.iloc[[0,50,100,150,200,250,300,400,500] , [0,3,6]].mean()
avg

survived     0.222222
age         27.428571
fare        12.049533
dtype: float64

In [24]:
deviation = df.iloc[[0,50,100,150,200,250,300,400,500] , [0,3,6]] - avg
deviation

     survived        age       fare
0   -0.222222  -5.428571  -4.799533
50  -0.222222 -20.428571  27.637967
100 -0.222222   0.571429  -4.153733
150 -0.222222  23.571429   0.475467
200 -0.222222   0.571429  -2.549533
250 -0.222222        NaN  -4.799533
300  0.777778        NaN  -4.299533
400  0.777778  11.571429  -4.124533
500 -0.222222 -10.428571  -3.387033

In [26]:
abs_dev = -deviation
abs_dev

     survived        age       fare
0    0.222222   5.428571   4.799533
50   0.222222  20.428571 -27.637967
100  0.222222  -0.571429   4.153733
150  0.222222 -23.571429  -0.475467
200  0.222222  -0.571429   2.549533
250  0.222222        NaN   4.799533
300 -0.777778        NaN   4.299533
400 -0.777778 -11.571429   4.124533
500  0.222222  10.428571   3.387033

In [20]:
df.iloc[2:700 , 2:7]

        sex   age  sibsp  parch      fare
2    female  26.0      0      0    7.9250
3    female  35.0      1      0   53.1000
4      male  35.0      0      0    8.0500
5      male   NaN      0      0    8.4583
6      male  54.0      0      0   51.8625
..      ...   ...    ...    ...       ...
695    male  52.0      0      0   13.5000
696    male  44.0      0      0    8.0500
697  female   NaN      0      0    7.7333
698    male  49.0      1      1  110.8833
699    male  42.0      0      0    7.6500

[698 rows x 5 columns]