In [2]:
import pandas as pd

In [3]:
# create dataset and create Series ,create DataFrame , build csv file , read_csv(file) 
data = {
    'Name':['Mike_Hertz' , 'Andrew' , 'John' , 'Altman' , 'adrIENNE'],
    'Age':[30 , 40 , 44 , 29 , 43],
    'Gender':[1 , 1 , 1 , 1 , 0],
    'Discharge Date':['2024-02-02' , '2019-08-26' , '2022-10-07' , '2020-12-18' , '2022-10-09'],
    'Medication':['Paracetamol' , 'Ibuprofen' , 'Aspirin' , 'Ibuprofen' , 'Penicillin'],
    'Test Results':['Normal' , 'Inconclusive' , 'Normal' , 'Abnormal' , ' Abnormal']
}

s = pd.Series(data)
s

Name                   [Mike_Hertz, Andrew, John, Altman, adrIENNE]
Age                                            [30, 40, 44, 29, 43]
Gender                                              [1, 1, 1, 1, 0]
Discharge Date    [2024-02-02, 2019-08-26, 2022-10-07, 2020-12-1...
Medication        [Paracetamol, Ibuprofen, Aspirin, Ibuprofen, P...
Test Results      [Normal, Inconclusive, Normal, Abnormal,  Abno...
dtype: object

In [4]:
# create DataFrame
df = pd.DataFrame(s , columns=['PatientData'])
df

                                                      PatientData
Name                 [Mike_Hertz, Andrew, John, Altman, adrIENNE]
Age                                          [30, 40, 44, 29, 43]
Gender                                            [1, 1, 1, 1, 0]
Discharge Date  [2024-02-02, 2019-08-26, 2022-10-07, 2020-12-1...
Medication      [Paracetamol, Ibuprofen, Aspirin, Ibuprofen, P...
Test Results    [Normal, Inconclusive, Normal, Abnormal,  Abno...

In [5]:
df.to_csv('PatientHistory.csv')

In [6]:
df = pd.read_csv(r'C:\Users\Muhammad Yahya\Downloads\python\Pandas\PatientHistory.csv',index_col=0) #r means row data
df

                                                      PatientData
Name            ['Mike_Hertz', 'Andrew', 'John', 'Altman', 'ad...
Age                                          [30, 40, 44, 29, 43]
Gender                                            [1, 1, 1, 1, 0]
Discharge Date  ['2024-02-02', '2019-08-26', '2022-10-07', '20...
Medication      ['Paracetamol', 'Ibuprofen', 'Aspirin', 'Ibupr...
Test Results    ['Normal', 'Inconclusive', 'Normal', 'Abnormal...

In [7]:
# call particular column using 'Method:1'
c = df['PatientData']
c

Name              ['Mike_Hertz', 'Andrew', 'John', 'Altman', 'ad...
Age                                            [30, 40, 44, 29, 43]
Gender                                              [1, 1, 1, 1, 0]
Discharge Date    ['2024-02-02', '2019-08-26', '2022-10-07', '20...
Medication        ['Paracetamol', 'Ibuprofen', 'Aspirin', 'Ibupr...
Test Results      ['Normal', 'Inconclusive', 'Normal', 'Abnormal...
Name: PatientData, dtype: object

In [8]:
pat_age = df['PatientData'].Age

print(pat_age)
print(type(pat_age))

[30, 40, 44, 29, 43]
<class 'str'>

In [9]:
pat_age = df['PatientData'].Age[1:]
print(pat_age)

30, 40, 44, 29, 43]

In [10]:
pat_age = df['PatientData'].Age[-5:-1]
print(pat_age)

, 43

In [11]:
pat_age = df['PatientData'].Medication[0]
pat_age

'['

In [12]:
print(type(pat_age))

<class 'str'>