In [2]:
import pandas as pd

In [3]:
bricks = {
    "country" : ['Brazil' , 'Russia' , 'India' , 'China' , 'South Africa'],
    "capital" : ['Brazil' , 'Moscow' , 'New Delhi' , 'Beijing' , 'Pretoria'],
    "area" : [8.516 , 17.100 , 3.286 , 9.597 , 1.221],
    "population" : [200.40 , 143.50 , 1252.00 , 1357.00 , 52.98]
}

In [4]:
# Build Dataframe in Above Data
df = pd.DataFrame(bricks)
df

        country    capital    area  population
0        Brazil     Brazil   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [5]:
# BUILD CSV FILE from above Dataframe:
df.to_csv("country information.csv")

In [6]:
call_csv = pd.read_csv(r'C:\Users\Muhammad Yahya\Downloads\python\Pandas\country information.csv' , index_col=[0])
df = call_csv 
df

        country    capital    area  population
0        Brazil     Brazil   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [7]:
df.index = ['BR','RU','IN','CH','SA']
df

         country    capital    area  population
BR        Brazil     Brazil   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [8]:
# call column one 
df['country']

BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [9]:
# call column one but show proper DataFrame
df[['country']]

         country
BR        Brazil
RU        Russia
IN         India
CH         China
SA  South Africa

In [10]:
# call first two column
df[['country','capital']]

         country    capital
BR        Brazil     Brazil
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

In [11]:
df['country','capital'] #Error

KeyError: ('country', 'capital')

In [ ]:
# first two rows 
df[0:2]

   country capital    area  population
BR  Brazil  Brazil   8.516       200.4
RU  Russia  Moscow  17.100       143.5

In [ ]:
# any three rows 
df[2:]

         country    capital   area  population
IN         India  New Delhi  3.286     1252.00
CH         China    Beijing  9.597     1357.00
SA  South Africa   Pretoria  1.221       52.98

In [ ]:
# negative indexing 
df = df[-3:-1]
df

   country    capital   area  population
IN   India  New Delhi  3.286      1252.0
CH   China    Beijing  9.597      1357.0

In [26]:
df[:-1]

   country    capital    area  population
BR  Brazil     Brazil   8.516       200.4
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [27]:
df[1:]

         country    capital    area  population
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
df[::-1] #reverse dataset

         country    capital    area  population
SA  South Africa   Pretoria   1.221       52.98
CH         China    Beijing   9.597     1357.00
IN         India  New Delhi   3.286     1252.00
RU        Russia     Moscow  17.100      143.50
BR        Brazil     Brazil   8.516      200.40

In [33]:
df[1:]

         country    capital    area  population
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [46]:
# print first two rows & only first column 
df[0:2][['country']]

   country
BR  Brazil
RU  Russia

# loc function

In [47]:
df.loc['IN']

country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object

In [50]:
df.loc['BR']

country       Brazil
capital       Brazil
area           8.516
population     200.4
Name: BR, dtype: object

In [52]:
df.loc['SA']

country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object

In [53]:
df.loc['BR']

country       Brazil
capital       Brazil
area           8.516
population     200.4
Name: BR, dtype: object

In [54]:
df.loc['CH']

country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object